vim.keymap.set("n", "<leader>a", "<cmd>WintabsPrevious<cr>")
vim.keymap.set("n", "<leader>f", "<cmd>WintabsNext<cr>")

vim.keymap.set("n", "<leader>1", "<cmd>WintabsFirst<cr>")
vim.keymap.set("n", "<leader>2", "<cmd>WintabsGo 2<cr>")
vim.keymap.set("n", "<leader>3", "<cmd>WintabsGo 3<cr>")
vim.keymap.set("n", "<leader>4", "<cmd>WintabsGo 4<cr>")
vim.keymap.set("n", "<leader>5", "<cmd>WintabsGo 5<cr>")
vim.keymap.set("n", "<leader>6", "<cmd>WintabsGo 6<cr>")
vim.keymap.set("n", "<leader>7", "<cmd>WintabsGo 7<cr>")
vim.keymap.set("n", "<leader>8", "<cmd>WintabsGo 8<cr>")
vim.keymap.set("n", "<leader>9", "<cmd>WintabsGo 9<cr>")
vim.keymap.set("n", "<leader>0", "<cmd>WintabsLast<cr>")
