vim.cmd("autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType lua setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType typescript setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType json setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType vue setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType vue syntax sync fromstart")
vim.cmd("autocmd FileType sh setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType go setlocal ts=2 sts=2 sw=2 noexpandtab")
vim.cmd("autocmd FileType php setlocal ts=4 sts=4 sw=4 noexpandtab")
vim.cmd("autocmd FileType vcl setlocal ts=4 sts=4 sw=4 expandtab")
vim.cmd("autocmd FileType xml setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType java setlocal ts=2 sts=2 sw=2 expandtab")
vim.cmd("autocmd FileType conf setlocal ts=4 sts=4 sw=4 expandtab")

vim.cmd("au BufNewFile,BufRead Jenkinsfile setf groovy")
vim.cmd("autocmd FileType Jenkinsfile setlocal ts=2 sts=2 sw=2 noexpandtab")
