
# Docs at: https://alacritty.org/config-alacritty.html

[window]

opacity = 0.98

padding.x = 0
padding.y = 0

decorations = "Full"
#decorations_theme_variant = "Light" # "Dark"
decorations_theme_variant = "Dark"

[font]
# you need nerd-fonts - https://github.com/ryanoasis/nerd-fonts
normal.family = "FiraCode Nerd Font Propo"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 10.0

[colors]
  # Default colors
  #primary.background = '0x002635'
  primary.background = '0x262626'
  #primary.foreground = '0xe6e6dc'
  primary.foreground = '0xe4e4e4'

  # Normal colors
  #normal.black = '0x00384d'
  normal.black = '0x262626'
  #normal.red = '0xc43061'
  normal.red = '0xff875f'
  #normal.green = '0x7fc06e'
  normal.green = '0xaeff87'
  #normal.yellow = '0xf08e48'
  normal.yellow = '0xf08e48'
  #normal.blue = '0x1c8db2'
  normal.blue = '0x1c8db2'
  #normal.magenta = '0xc694ff'
  normal.magenta = '0xc694ff'
  #normal.cyan = '0x00cccc'
  normal.cyan = '0x00cccc'
  normal.white = '0x77929e'

  ## Bright colors
  bright.black = '0x517f8d'
  bright.red = '0xff5a67'
  bright.green = '0x9cf087'
  bright.yellow = '0xffcc1b'
  bright.blue = '0x7eb2dd'
  bright.magenta = '0xfb94ff'
  bright.cyan = '0x00ffff'
  bright.white  = '0xb7cff9'

  #cursor
  cursor.text = "0x002635"
  cursor.cursor = "0xffcc1b"
